title: NYUADIM
default_lang: en
author:
  name: 'James Hosken'
  email: nyuad.im@nyu.edu
taxonomies:
  - category
  - tag
metadata:
  nyuadim: 'A hub of interaction, community, and learning'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /lab: /resources/lab
  /people: /resources/people
blog:
  route: /blog
